name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to the HYREL COC_Generator! Thank you for your first issue!"
        pr-message: "Thanks for contributing to the HYREL COC_Generator! Please notify the maintainer if you haven't already!"
